In [2]:
#对资产负债表
import pandas as pd
# 定义要保留纵坐标的 Excel 文件
reference_file = 'data\df_sum_2017.xlsx'
# 定义要合并的其他 Excel 文件列表
file_list = ['data\df_sum_2018.xlsx', 'data\df_sum_2019.xlsx', 'data\df_sum_2020.xlsx', 'data\df_sum_2021.xlsx', 'data\df_sum_2022.xlsx']
# 读取参考文件的数据
merged_data = pd.read_excel(reference_file, index_col=0)
# 循环遍历其他文件，并将它们的数据与参考文件的索引匹配后合并
for file in file_list:
    data = pd.read_excel(file, index_col=0)
    merged_data = merged_data.merge(data, left_index=True, right_index=True)
# 重命名列名称为 "2017" 到 "2022"
merged_data.columns = [str(year) for year in range(2017, 2023)]
# 将合并后的数据保存到一个新的 Excel 文件
merged_data.to_excel('data\merged.xlsx')
print("合并完成！")

合并完成！

C:\Users\belle\AppData\Local\Temp\ipykernel_3092\669982100.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_data = merged_data.merge(data, left_index=True, right_index=True)
C:\Users\belle\AppData\Local\Temp\ipykernel_3092\669982100.py:12: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  merged_data = merged_data.merge(data, left_index=True, right_index=True)

In [4]:
#数据计算
data = pd.read_excel('data\merged.xlsx')
# 转置 DataFrame
df_transposed = data.transpose()
df_transposed
# 删除指定行
df_transposed = df_transposed.drop('Unnamed: 0')
df_transposed
# 设置正确的列名
df_transposed.columns = ["流动资产合计", "非流动资产合计", "资产总计", "流动负债合计", "非流动负债合计", "负债合计", "所有者权益(或股东权益)合计", "负债和所有者权益(或股东权益)总计"]
df_transposed

,流动资产合计,非流动资产合计,资产总计,流动负债合计,非流动负债合计,负债合计,所有者权益(或股东权益)合计,负债和所有者权益(或股东权益)总计
2017,372059.34,119838.81,491898.15,259252.33,936.91,260189.24,231708.91,491898.15
2018,990543.69,229010.49,1219554.17,514464.02,3407.25,517871.27,701682.91,1219554.17
2019,1208332.34,424729.36,1633061.71,622405.56,6105.76,628511.32,1004550.4,1633061.71
2020,1484318.53,459017.46,1943335.99,841739.63,4088.05,845827.68,1097508.33,1943335.99
2021,2749077.77,572218.61,3321296.38,1569108.23,101451.58,1670559.82,1650736.57,3321296.38
2022,3957888.6,767934.97,4725823.56,1946676.66,413602.98,2360279.64,2365543.92,4725823.56

In [5]:
# 将相关列转换为数值类型
df_transposed[['流动资产合计', '非流动资产合计', '资产总计','流动负债合计','非流动负债合计','负债合计','所有者权益(或股东权益)合计','负债和所有者权益(或股东权益)总计']] = df_transposed[['流动资产合计', '非流动资产合计', '资产总计','流动负债合计','非流动负债合计','负债合计','所有者权益(或股东权益)合计','负债和所有者权益(或股东权益)总计']].astype(float)

In [8]:
# 计算流动资产占比和非流动资产占比
df_transposed['流动资产占比'] = df_transposed['流动资产合计'] / df_transposed['资产总计']
df_transposed['非流动资产占比'] = df_transposed['非流动资产合计'] / df_transposed['资产总计']
# 计算流动负债占比、非流动负债占比和所有者权益占比
df_transposed['流动负债占比'] = df_transposed['流动负债合计'] / df_transposed['负债合计']
df_transposed['非流动负债占比'] = df_transposed['非流动负债合计'] / df_transposed['负债合计']
df_transposed['所有者权益占比'] = df_transposed['所有者权益(或股东权益)合计'] / df_transposed['负债和所有者权益(或股东权益)总计']
df_transposed.to_excel('data\pre_merged.xlsx')

In [9]:
# 利润表
import pandas as pd

# 从Excel文件读取数据并创建DataFrame
df = pd.read_excel("data\data_2013_2022.xlsx", sheet_name=None)

# 创建一个空列表，用于存储处理后的数据
new_dfs = []

# 遍历每个工作表
for sheet_name, sheet_df in df.items():
    # 选择营业收入和营业利润所在的行
    revenue_row = sheet_df.iloc[0]
    profit_row = sheet_df.iloc[1]

    # 提取日期列和营业收入、营业利润列
    dates = revenue_row.index[1:]
    revenue_values = revenue_row.values[1:]
    profit_values = profit_row.values[1:]

    # 将营业收入和营业利润转换为float并相加
    revenue_sum = sum([float(value.replace(",", "")) for value in revenue_values])
    profit_sum = sum([float(value.replace(",", "")) for value in profit_values])

    # 创建新的DataFrame
    new_df = pd.DataFrame({
        "日期": dates,
        "营业收入总和": [revenue_sum] * len(dates),
        "营业利润总和": [profit_sum] * len(dates)
    })

    # 保留第一行数据
    new_df = new_df.iloc[:1, :]

    # 将日期改为工作表的名称
    new_df["日期"] = sheet_name

    # 将新的DataFrame添加到列表中
    new_dfs.append(new_df)

# 将所有处理后的数据合并为一个DataFrame
final_df = pd.concat(new_dfs)

# 打印最终的DataFrame
print(final_df)

     日期      营业收入总和     营业利润总和
0  2013   194543.98   19080.39
0  2014   231386.10   18490.07
0  2015   269483.98   20515.22
0  2016   542584.25   15732.22
0  2017   944358.52   91191.66
0  2018  1317879.76  125747.34
0  2019  1243209.47   49246.68
0  2020  1474053.55  122682.01
0  2021  2891367.15  511917.15
0  2022  3547301.67  448291.00

In [10]:
# 计算营业收入的环比增长率
final_df["营业收入环比增长率"] = final_df["营业收入总和"].pct_change() * 100

# 计算营业利润的环比增长率
final_df["营业利润环比增长率"] = final_df["营业利润总和"].pct_change() * 100

# 打印计算后的DataFrame
final_df

     日期      营业收入总和     营业利润总和   营业收入环比增长率   营业利润环比增长率
0  2013   194543.98   19080.39         NaN         NaN
0  2014   231386.10   18490.07   18.937682   -3.093857
0  2015   269483.98   20515.22   16.465069   10.952636
0  2016   542584.25   15732.22  101.341931  -23.314398
0  2017   944358.52   91191.66   74.048274  479.649026
0  2018  1317879.76  125747.34   39.552906   37.893465
0  2019  1243209.47   49246.68   -5.665941  -60.836802
0  2020  1474053.55  122682.01   18.568398  149.117321
0  2021  2891367.15  511917.15   96.150754  317.271571
0  2022  3547301.67  448291.00   22.685964  -12.428994

In [13]:
final_df.to_excel('data\pre_data.xlsx')